// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using voxpopuli.Dati;

namespace voxpopuli.Migrations
{
    [DbContext(typeof(VoxPopuliDbContext))]
    partial class VoxPopuliDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("voxpopuli.Dati.Segnalazione", b =>
                {
                    b.Property<int>("SegnalazioneId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataSegnalazione");

                    b.Property<string>("Descrizione")
                        .IsRequired();

                    b.Property<bool>("PresaInCarico");

                    b.Property<string>("Proprietario");

                    b.Property<bool>("Risolta");

                    b.HasKey("SegnalazioneId");

                    b.HasIndex("Descrizione");

                    b.ToTable("Segnalazioni");
                });

            modelBuilder.Entity("voxpopuli.Dati.Suggerimento", b =>
                {
                    b.Property<int>("SuggerimentoId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<string>("Descrizione")
                        .IsRequired();

                    b.Property<string>("Titolo")
                        .IsRequired();

                    b.Property<int>("Voti");

                    b.HasKey("SuggerimentoId");

                    b.HasIndex("Data");

                    b.HasIndex("Descrizione");

                    b.HasIndex("Titolo");

                    b.ToTable("Suggerimenti");
                });
#pragma warning restore 612, 618
        }
    }
}
